
import type { User, Listing } from './types';

const gordonFreeman: User = {
    name: 'Gordon Freeman',
    username: 'gfreeman',
    avatarUrl: 'https://i.pravatar.cc/150?u=gordon',
    status: 'verified',
    reviews: [
        { rating: 5, comment: 'Great seller, item was exactly as described!', buyerName: 'barney', date: '2023-10-15T10:00:00Z' },
        { rating: 4, comment: 'Good communication, fast shipping.', buyerName: 'alyx', date: '2023-09-22T14:30:00Z' },
    ],
    idNumber: 'ID123456789',
    idDocumentUrl: 'https://placehold.co/800x500/EFEFEF/333?text=Verified+ID+Document',
    location: 'Cape Town, WC',
    aiAutoReplyEnabled: true,
};

const alyxVance: User = {
    name: 'Alyx Vance',
    username: 'alyx',
    avatarUrl: 'https://i.pravatar.cc/150?u=alyx',
    status: 'verified',
    reviews: [
        { rating: 5, comment: 'Excellent seller, would buy from again.', buyerName: 'gordon', date: '2023-11-01T11:00:00Z' }
    ],
    idNumber: 'ID987654321',
    idDocumentUrl: 'https://placehold.co/800x500/EFEFEF/333?text=Verified+ID+Document',
    location: 'Johannesburg, GP',
    aiAutoReplyEnabled: true,
};

const barneyCalhoun: User = {
    name: 'Barney Calhoun',
    username: 'barney',
    avatarUrl: 'https://i.pravatar.cc/150?u=barney',
    status: 'unverified',
    location: 'Durban, KZN',
    aiAutoReplyEnabled: false,
};

const gMan: User = {
    name: 'G Man',
    username: 'gman',
    avatarUrl: 'https://i.pravatar.cc/150?u=gman',
    status: 'verified',
    idNumber: 'ID000000001',
    idDocumentUrl: 'https://placehold.co/800x500/EFEFEF/333?text=Verified+ID+Document',
    location: 'Pretoria, GP',
    reviews: [],
    aiAutoReplyEnabled: false,
};

export const mockListings: Listing[] = [
    {
        id: '1',
        title: 'Vintage Leather Armchair',
        price: 2500,
        description: 'A beautiful and comfortable vintage leather armchair. Perfect for a reading nook. Minor wear and tear consistent with age, but in great condition overall. Collection only.',
        imageUrls: [
            'https://picsum.photos/seed/armchair1/800/600',
            'https://picsum.photos/seed/armchair2/800/600',
            'https://picsum.photos/seed/armchair3/800/600',
        ],
        seller: gordonFreeman,
        category: 'Furniture',
        status: 'available',
        sellerAddress: 'Cape Town, WC',
        chatHistory: [
            { senderUsername: 'alyx', text: 'Hi, is this still available?', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
            { senderUsername: 'gfreeman', text: 'Yes it is!', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(), status: 'read' },
        ]
    },
    {
        id: '2',
        title: 'Acoustic Guitar with Case',
        price: 1800,
        description: 'Yamaha F310 acoustic guitar. Great for beginners. Comes with a soft case, a few picks, and a tuner. Barely used, strings are in good shape.',
        imageUrls: ['https://picsum.photos/seed/guitar/800/600'],
        seller: alyxVance,
        category: 'Musical Instruments',
        status: 'available',
        sellerAddress: 'Johannesburg, GP',
    },
    {
        id: '3',
        title: 'Nintendo Switch Console',
        price: 4500,
        description: 'Original Nintendo Switch console with dock, joy-cons, and all original cables. Screen protector has been on since day one. Works perfectly. No games included.',
        imageUrls: ['https://picsum.photos/seed/switch/800/600'],
        videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        seller: barneyCalhoun,
        category: 'Electronics',
        status: 'sold',
        sellerAddress: 'Durban, KZN',
        buyerName: 'gfreeman',
        buyerAvatarUrl: gordonFreeman.avatarUrl,
        reviewLeft: true,
    },
    {
        id: '4',
        title: 'Set of 4 Contemporary Dining Chairs',
        price: 3200,
        description: 'Sleek and modern dining chairs. Grey fabric with black metal legs. Very sturdy and comfortable. Selling as a set of 4 only. No stains or damage.',
        imageUrls: [
            'https://picsum.photos/seed/chairs1/800/600',
            'https://picsum.photos/seed/chairs2/800/600',
        ],
        seller: gMan,
        category: 'Furniture',
        status: 'available',
        sellerAddress: 'Pretoria, GP',
    },
    {
        id: '5',
        title: 'Professional Camera Drone',
        price: 8500,
        description: 'DJI Mavic Air 2 drone. Captures stunning 4K video. Comes with the fly-more combo: 3 batteries, charging hub, extra propellers, and carrying case. No crashes, in excellent condition.',
        imageUrls: ['https://picsum.photos/seed/drone/800/600'],
        seller: alyxVance,
        category: 'Electronics',
        status: 'available',
        sellerAddress: 'Johannesburg, GP',
    },
    {
        id: '6',
        title: 'Mountain Bike - Large Frame',
        price: 6000,
        description: 'Silverback Stride Mountain Bike. 29" wheels, large frame. Recently serviced. Great for trails. Selling because I am upgrading.',
        imageUrls: ['https://picsum.photos/seed/bike/800/600'],
        seller: gordonFreeman,
        category: 'Sporting Goods',
        status: 'pending',
        sellerAddress: 'Cape Town, WC',
        buyerName: 'gman',
        buyerAvatarUrl: gMan.avatarUrl,
    },
    {
        id: '7',
        title: 'Retro Polaroid Camera',
        price: 750,
        description: 'Original Polaroid 600 camera from the 90s. A fun, retro gadget for instant photos. Tested and working. Film not included.',
        imageUrls: ['https://picsum.photos/seed/polaroid/800/600'],
        seller: alyxVance,
        category: 'Electronics',
        status: 'available',
        sellerAddress: 'Johannesburg, GP',
    },
    {
        id: '8',
        title: 'Designer Leather Handbag',
        price: 3800,
        description: 'Authentic designer handbag in black leather. Used a few times, but in pristine condition. Comes with original dust bag.',
        imageUrls: [],
        seller: barneyCalhoun,
        category: 'Clothing & Accessories',
        status: 'available',
        sellerAddress: 'Durban, KZN',
    },
    {
        id: '9',
        title: 'Smeg Retro Kettle - Cream',
        price: 1500,
        description: 'Iconic Smeg 50s style kettle in cream color. Works perfectly, recently descaled. A stylish addition to any kitchen.',
        imageUrls: ['https://picsum.photos/seed/kettle/800/600'],
        videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        seller: gordonFreeman,
        category: 'Appliances',
        status: 'sold',
        sellerAddress: 'Cape Town, WC',
        buyerName: 'alyx',
        buyerAvatarUrl: alyxVance.avatarUrl,
        reviewLeft: false,
    },
    {
        id: '10',
        title: 'Hardcover Book Collection (Sci-Fi)',
        price: 600,
        description: 'Collection of 8 classic science fiction novels in hardcover. Includes titles by Asimov, Clarke, and Herbert. All in good, readable condition.',
        imageUrls: ['https://picsum.photos/seed/books/800/600'],
        seller: gMan,
        category: 'Books & Media',
        status: 'available',
        sellerAddress: 'Pretoria, GP',
    },
];